package com.corp.todo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Task implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Task() {
    }




}